package governance

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/cogitave/clawtool/internal/setup"
)

const codeownersPath = ".github/CODEOWNERS"

type codeownersRecipe struct{}

func (codeownersRecipe) Meta() setup.RecipeMeta {
	return setup.RecipeMeta{
		Name:        "codeowners",
		Category:    setup.CategoryGovernance,
		Description: "Generates .github/CODEOWNERS from a list of owners and optional per-path rules.",
		Upstream:    "spec:https://docs.github.com/en/repositories/managing-your-repositories-settings-and-features/customizing-your-repository/about-code-owners",
		Stability:   setup.StabilityStable,
	}
}

func (codeownersRecipe) Detect(_ context.Context, repo string) (setup.Status, string, error) {
	path := filepath.Join(repo, codeownersPath)
	b, err := setup.ReadIfExists(path)
	if err != nil {
		return setup.StatusError, "", err
	}
	if b == nil {
		return setup.StatusAbsent, ".github/CODEOWNERS not present", nil
	}
	if setup.HasMarker(b, setup.ManagedByMarker) {
		return setup.StatusApplied, "managed-by: clawtool marker present", nil
	}
	return setup.StatusPartial, "CODEOWNERS exists but is not clawtool-managed; Apply will refuse to overwrite", nil
}

func (codeownersRecipe) Prereqs() []setup.Prereq { return nil }

func (codeownersRecipe) Apply(_ context.Context, repo string, opts setup.Options) error {
	owners := stringSliceOption(opts, "owners")
	if len(owners) == 0 {
		return fmt.Errorf("codeowners recipe requires opts[owners] (non-empty []string of @handles)")
	}

	path := filepath.Join(repo, codeownersPath)
	existing, err := setup.ReadIfExists(path)
	if err != nil {
		return err
	}
	if existing != nil && !setup.HasMarker(existing, setup.ManagedByMarker) {
		return fmt.Errorf("%s exists but is not clawtool-managed; refusing to overwrite", codeownersPath)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", setup.ManagedByMarker)
	b.WriteString("# Generated by `clawtool recipe apply codeowners`.\n")
	b.WriteString("# Edits are safe — re-running the recipe refuses to overwrite an unmanaged file.\n")
	b.WriteString("# Remove the managed-by line above to make this file fully your own.\n\n")

	paths := mapSliceOption(opts, "paths")
	if len(paths) == 0 {
		fmt.Fprintf(&b, "* %s\n", strings.Join(owners, " "))
	} else {
		// Catch-all first so per-path rules below override it (last
		// matching rule wins per GitHub spec).
		fmt.Fprintf(&b, "* %s\n", strings.Join(owners, " "))
		b.WriteString("\n")
		for _, rule := range paths {
			pat, _ := rule["pattern"].(string)
			ruleOwners := stringSliceFromAny(rule["owners"])
			if pat == "" || len(ruleOwners) == 0 {
				continue
			}
			fmt.Fprintf(&b, "%s %s\n", pat, strings.Join(ruleOwners, " "))
		}
	}
	return setup.WriteAtomic(path, []byte(b.String()), 0o644)
}

func (codeownersRecipe) Verify(_ context.Context, repo string) error {
	path := filepath.Join(repo, codeownersPath)
	b, err := setup.ReadIfExists(path)
	if err != nil {
		return fmt.Errorf("verify: %w", err)
	}
	if b == nil {
		return fmt.Errorf("verify: %s missing", codeownersPath)
	}
	if !setup.HasMarker(b, setup.ManagedByMarker) {
		return fmt.Errorf("verify: clawtool marker missing in %s", codeownersPath)
	}
	return nil
}

// stringSliceOption pulls a []string from opts. Accepts both
// []string (when called from Go) and []any (when called from MCP /
// JSON-decoded input).
func stringSliceOption(opts setup.Options, key string) []string {
	if v, ok := setup.GetOption[[]string](opts, key); ok {
		return v
	}
	if v, ok := setup.GetOption[[]any](opts, key); ok {
		return stringSliceFromAny(v)
	}
	return nil
}

func stringSliceFromAny(v any) []string {
	arr, ok := v.([]any)
	if !ok {
		if s, ok := v.([]string); ok {
			return s
		}
		return nil
	}
	out := make([]string, 0, len(arr))
	for _, x := range arr {
		if s, ok := x.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func mapSliceOption(opts setup.Options, key string) []map[string]any {
	if v, ok := setup.GetOption[[]map[string]any](opts, key); ok {
		return v
	}
	if v, ok := setup.GetOption[[]any](opts, key); ok {
		out := make([]map[string]any, 0, len(v))
		for _, x := range v {
			if m, ok := x.(map[string]any); ok {
				out = append(out, m)
			}
		}
		return out
	}
	return nil
}

func init() { setup.Register(codeownersRecipe{}) }
