package sources

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestTODOs_FindsCommentMarkers writes a small Go file with a mix
// of TODO / FIXME / XXX / unrelated comments and asserts the source
// returns one Idea per actionable marker — no false positives on
// the unrelated comments.
func TestTODOs_FindsCommentMarkers(t *testing.T) {
	dir := t.TempDir()
	body := strings.Join([]string{
		"package fake",
		"",
		"// TODO: split this struct",
		"// FIXME(arda): null check missing",
		"// XXX legacy compat",
		"// not actionable",
		"//TODO no-space variant",
		"// godoc-style trailing TODO sentence — should not match",
		"",
		"func F() {} // TODO inline",
		"",
	}, "\n")
	if err := os.WriteFile(filepath.Join(dir, "fake.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	// Drop a generated file alongside; its TODO must NOT surface.
	gen := "// Code generated by foo. DO NOT EDIT.\npackage fake\n// TODO ignored generated\n"
	if err := os.WriteFile(filepath.Join(dir, "gen.go"), []byte(gen), 0o644); err != nil {
		t.Fatalf("write gen: %v", err)
	}

	src := NewTODOs()
	ideas, err := src.Scan(context.Background(), dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	// Expect: TODO / FIXME / XXX / no-space TODO / inline TODO = 5.
	if len(ideas) < 4 {
		t.Fatalf("Scan returned %d ideas, want >= 4: %v", len(ideas), ideaTitles(ideas))
	}
	// Verify each marker type surfaced at least once.
	for _, want := range []string{"TODO", "FIXME", "XXX"} {
		found := false
		for _, idea := range ideas {
			if strings.HasPrefix(idea.Title, want+":") {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("no idea for marker %q in %v", want, ideaTitles(ideas))
		}
	}
	// FIXME must score higher than TODO (priority 5 vs 3).
	for _, idea := range ideas {
		if strings.HasPrefix(idea.Title, "FIXME:") && idea.SuggestedPriority < 5 {
			t.Fatalf("FIXME priority %d, want >= 5", idea.SuggestedPriority)
		}
	}
	// Generated file's TODO must not appear.
	for _, idea := range ideas {
		if strings.Contains(idea.Evidence, "gen.go") {
			t.Fatalf("generated file leaked: %+v", idea)
		}
	}
}

// TestTODOs_RespectsMaxIdeas caps the source's emit count.
func TestTODOs_RespectsMaxIdeas(t *testing.T) {
	dir := t.TempDir()
	var lines []string
	lines = append(lines, "package fake")
	for i := 0; i < 25; i++ {
		lines = append(lines, "// TODO item "+itoa(i))
	}
	if err := os.WriteFile(filepath.Join(dir, "fake.go"), []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	src := NewTODOs()
	src.MaxIdeas = 5
	ideas, err := src.Scan(context.Background(), dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(ideas) != 5 {
		t.Fatalf("Scan returned %d ideas, want 5", len(ideas))
	}
}

// TestTodos_SkipsVendoredAndCachePaths exercises the path-fragment
// exclusion list added in v0.22.120. Operator reported leakage from
// Go module cache (`go/pkg/mod/...`), Claude Code plugin cache
// (`.claude/plugins/...`), Obsidian wiki, and node_modules when
// `clawtool ideate` was run from $HOME. Walker must drop those
// branches and only return TODOs from real source paths.
func TestTodos_SkipsVendoredAndCachePaths(t *testing.T) {
	root := t.TempDir()

	type fixture struct {
		rel  string
		body string
	}
	fixtures := []fixture{
		{"go/pkg/mod/github.com/!masterminds/semver/foo.go", "package foo\n// TODO leaked module-cache TODO\n"},
		{".claude/plugins/marketplaces/clawtool-marketplace/x.go", "package x\n// TODO leaked plugin-install TODO\n"},
		{".claude/plugins/cache/clawtool-marketplace/clawtool/0.21.3/y.go", "package y\n// TODO leaked plugin-cache TODO\n"},
		{"vendor/example.com/foo/bar.go", "package bar\n// TODO leaked vendor TODO\n"},
		{"node_modules/some-pkg/index.go", "package idx\n// TODO leaked node_modules TODO\n"},
		{"wiki/decisions/035-foo.go", "package wiki\n// TODO leaked wiki TODO\n"},
		// Real source — must surface.
		{"internal/cli/x.go", "package cli\n// TODO real source TODO\n"},
	}
	for _, f := range fixtures {
		full := filepath.Join(root, f.rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(full), err)
		}
		if err := os.WriteFile(full, []byte(f.body), 0o644); err != nil {
			t.Fatalf("write %s: %v", full, err)
		}
	}

	src := NewTODOs()
	ideas, err := src.Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(ideas) != 1 {
		titles := make([]string, len(ideas))
		for i, idea := range ideas {
			titles[i] = idea.Title + " @ " + idea.Evidence
		}
		t.Fatalf("Scan returned %d ideas, want 1: %v", len(ideas), titles)
	}
	if !strings.Contains(ideas[0].Evidence, "internal/cli/x.go") {
		t.Fatalf("surviving idea evidence = %q, want contains internal/cli/x.go", ideas[0].Evidence)
	}
	if strings.Contains(ideas[0].Title, "leaked") {
		t.Fatalf("leaked TODO surfaced: %q", ideas[0].Title)
	}
}

// itoa is a tiny helper so the test stays free of strconv.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{'0' + byte(n%10)}, b...)
		n /= 10
	}
	return string(b)
}
