package sources

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestTODOs_FindsCommentMarkers writes a small Go file with a mix
// of TODO / FIXME / XXX / unrelated comments and asserts the source
// returns one Idea per actionable marker — no false positives on
// the unrelated comments.
func TestTODOs_FindsCommentMarkers(t *testing.T) {
	dir := t.TempDir()
	body := strings.Join([]string{
		"package fake",
		"",
		"// TODO: split this struct",
		"// FIXME(arda): null check missing",
		"// XXX legacy compat",
		"// not actionable",
		"//TODO no-space variant",
		"// godoc-style trailing TODO sentence — should not match",
		"",
		"func F() {} // TODO inline",
		"",
	}, "\n")
	if err := os.WriteFile(filepath.Join(dir, "fake.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	// Drop a generated file alongside; its TODO must NOT surface.
	gen := "// Code generated by foo. DO NOT EDIT.\npackage fake\n// TODO ignored generated\n"
	if err := os.WriteFile(filepath.Join(dir, "gen.go"), []byte(gen), 0o644); err != nil {
		t.Fatalf("write gen: %v", err)
	}

	src := NewTODOs()
	ideas, err := src.Scan(context.Background(), dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	// Expect: TODO / FIXME / XXX / no-space TODO / inline TODO = 5.
	if len(ideas) < 4 {
		t.Fatalf("Scan returned %d ideas, want >= 4: %v", len(ideas), ideaTitles(ideas))
	}
	// Verify each marker type surfaced at least once.
	for _, want := range []string{"TODO", "FIXME", "XXX"} {
		found := false
		for _, idea := range ideas {
			if strings.HasPrefix(idea.Title, want+":") {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("no idea for marker %q in %v", want, ideaTitles(ideas))
		}
	}
	// FIXME must score higher than TODO (priority 5 vs 3).
	for _, idea := range ideas {
		if strings.HasPrefix(idea.Title, "FIXME:") && idea.SuggestedPriority < 5 {
			t.Fatalf("FIXME priority %d, want >= 5", idea.SuggestedPriority)
		}
	}
	// Generated file's TODO must not appear.
	for _, idea := range ideas {
		if strings.Contains(idea.Evidence, "gen.go") {
			t.Fatalf("generated file leaked: %+v", idea)
		}
	}
}

// TestTODOs_RespectsMaxIdeas caps the source's emit count.
func TestTODOs_RespectsMaxIdeas(t *testing.T) {
	dir := t.TempDir()
	var lines []string
	lines = append(lines, "package fake")
	for i := 0; i < 25; i++ {
		lines = append(lines, "// TODO item "+itoa(i))
	}
	if err := os.WriteFile(filepath.Join(dir, "fake.go"), []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	src := NewTODOs()
	src.MaxIdeas = 5
	ideas, err := src.Scan(context.Background(), dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(ideas) != 5 {
		t.Fatalf("Scan returned %d ideas, want 5", len(ideas))
	}
}

// itoa is a tiny helper so the test stays free of strconv.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{'0' + byte(n%10)}, b...)
		n /= 10
	}
	return string(b)
}
