// Package supplychain hosts recipes for the `supply-chain` category —
// dependency updates and security tooling. The package is named
// `supplychain` because Go forbids hyphens in package identifiers;
// the user-facing category remains `supply-chain`.
package supplychain

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/cogitave/clawtool/internal/setup"
)

const dependabotPath = ".github/dependabot.yml"

type dependabotRecipe struct{}

func (dependabotRecipe) Meta() setup.RecipeMeta {
	return setup.RecipeMeta{
		Name:        "dependabot",
		Category:    setup.CategorySupplyChain,
		Description: "Drops .github/dependabot.yml with weekly cadence for every package ecosystem detected in the repo.",
		Upstream:    "https://docs.github.com/en/code-security/dependabot",
		Stability:   setup.StabilityStable,
	}
}

func (dependabotRecipe) Detect(_ context.Context, repo string) (setup.Status, string, error) {
	path := filepath.Join(repo, dependabotPath)
	b, err := setup.ReadIfExists(path)
	if err != nil {
		return setup.StatusError, "", err
	}
	if b == nil {
		return setup.StatusAbsent, ".github/dependabot.yml not present", nil
	}
	if setup.HasMarker(b, setup.ManagedByMarker) {
		return setup.StatusApplied, "managed-by: clawtool marker present", nil
	}
	return setup.StatusPartial, "dependabot.yml exists but is not clawtool-managed; Apply will refuse to overwrite", nil
}

func (dependabotRecipe) Prereqs() []setup.Prereq { return nil }

// detectEcosystems probes repo for files that signal each Dependabot
// package-ecosystem. Order matches the conventional dependabot.yml
// layout (language ecosystems first, gh actions last).
func detectEcosystems(repo string) []string {
	var out []string
	probe := func(rel, ecosystem string) {
		full := filepath.Join(repo, rel)
		if exists, _ := setup.FileExists(full); exists {
			out = append(out, ecosystem)
		}
	}
	probe("go.mod", "gomod")
	if exists, _ := setup.FileExists(filepath.Join(repo, "package.json")); exists {
		out = append(out, "npm")
	}
	if exists, _ := setup.FileExists(filepath.Join(repo, "requirements.txt")); exists {
		out = append(out, "pip")
	} else if exists, _ := setup.FileExists(filepath.Join(repo, "pyproject.toml")); exists {
		out = append(out, "pip")
	}
	// gh-actions: workflows dir contents.
	if entries, err := readDir(filepath.Join(repo, ".github", "workflows")); err == nil && len(entries) > 0 {
		out = append(out, "github-actions")
	}
	return out
}

func (dependabotRecipe) Apply(_ context.Context, repo string, _ setup.Options) error {
	ecosystems := detectEcosystems(repo)
	if len(ecosystems) == 0 {
		return fmt.Errorf("no recognized package ecosystems found in %s (looked for go.mod, package.json, requirements.txt, pyproject.toml, .github/workflows)", repo)
	}

	path := filepath.Join(repo, dependabotPath)
	existing, err := setup.ReadIfExists(path)
	if err != nil {
		return err
	}
	if existing != nil && !setup.HasMarker(existing, setup.ManagedByMarker) {
		return fmt.Errorf("%s exists but is not clawtool-managed; refusing to overwrite", dependabotPath)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", setup.ManagedByMarker)
	b.WriteString("# Generated by `clawtool recipe apply dependabot`.\n")
	b.WriteString("# Edits are safe — re-running the recipe refuses to overwrite an unmanaged file.\n")
	b.WriteString("\n")
	b.WriteString("version: 2\n")
	b.WriteString("updates:\n")
	for _, eco := range ecosystems {
		fmt.Fprintf(&b, "  - package-ecosystem: %q\n", eco)
		b.WriteString("    directory: \"/\"\n")
		b.WriteString("    schedule:\n")
		b.WriteString("      interval: \"weekly\"\n")
		b.WriteString("    open-pull-requests-limit: 5\n")
	}
	return setup.WriteAtomic(path, []byte(b.String()), 0o644)
}

func (dependabotRecipe) Verify(_ context.Context, repo string) error {
	path := filepath.Join(repo, dependabotPath)
	b, err := setup.ReadIfExists(path)
	if err != nil {
		return fmt.Errorf("verify: %w", err)
	}
	if b == nil {
		return fmt.Errorf("verify: %s missing", dependabotPath)
	}
	if !setup.HasMarker(b, setup.ManagedByMarker) {
		return fmt.Errorf("verify: clawtool marker missing in %s", dependabotPath)
	}
	return nil
}

// readDir is a thin wrapper so detectEcosystems doesn't need to
// import os in two more places.
func readDir(path string) ([]string, error) {
	entries, err := osReadDir(path)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

func init() { setup.Register(dependabotRecipe{}) }
