// Package mcpgen — language-agnostic files every scaffolded
// project gets. .clawtool/mcp.toml is the discovery marker `mcp
// list` walks for; .claude-plugin/ is the optional manifest from
// ADR-019.
package mcpgen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// commonFiles returns the always-on artifacts: README, mcp.toml,
// .gitignore, the per-language `.github/workflows/ci.yml` template
// (ADR-019 §Resolved 2026-05-02), and (when spec.Plugin is true)
// the .claude-plugin/plugin.json + marketplace.json.template.
func commonFiles(spec Spec) []File {
	out := []File{
		{Path: ".clawtool/mcp.toml", Body: renderMcpToml(spec)},
		{Path: "README.md", Body: renderReadme(spec)},
		{Path: ".gitignore", Body: gitignoreFor(spec.Language)},
		{Path: ".github/workflows/ci.yml", Body: renderCIWorkflow(spec)},
	}
	if spec.Plugin {
		out = append(out, File{
			Path: ".claude-plugin/plugin.json",
			Body: renderClaudePlugin(spec),
		})
		out = append(out, File{
			Path: ".claude-plugin/marketplace.json.template",
			Body: renderMarketplaceTemplate(spec),
		})
	}
	return out
}

// renderCIWorkflow returns the body of `.github/workflows/ci.yml`
// for the given language. Workflows run on push to main + on PRs;
// concurrency cancels in-progress runs on the same branch so a
// fast-follow push doesn't queue.
//
// Per-language gates (kept minimal — operators extend after they
// add real code):
//
//   - Go:         setup-go@v6 with go.mod toolchain → `go mod download`
//     → `gofmt -l .` (fail on dirty) → `go vet ./...`
//     → `go test -race ./...`
//   - Python:     setup-python@v6 with pyproject pin → `pip install -e .[dev]`
//     → `ruff check .` → `pytest`
//   - TypeScript: setup-node@v6 → `pnpm install --frozen-lockfile`
//     → `pnpm test` → `pnpm lint`
func renderCIWorkflow(s Spec) string {
	switch strings.ToLower(s.Language) {
	case "python":
		return ciWorkflowPython()
	case "typescript":
		return ciWorkflowTypeScript()
	default:
		return ciWorkflowGo()
	}
}

func ciWorkflowGo() string {
	return `# Generated by ` + "`clawtool mcp new`" + `. Minimal CI gate per ADR-019.
# Extend with the checks your project actually needs.
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Download modules
        run: go mod download

      - name: gofmt
        run: |
          dirty=$(gofmt -l .)
          if [ -n "$dirty" ]; then
            echo "::error::gofmt found unformatted files:"
            echo "$dirty"
            exit 1
          fi

      - name: go vet
        run: go vet ./...

      - name: go test -race
        run: go test -race ./...
`
}

func ciWorkflowPython() string {
	return `# Generated by ` + "`clawtool mcp new`" + `. Minimal CI gate per ADR-019.
# Extend with the checks your project actually needs.
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install
        run: pip install -e .[dev]

      - name: ruff check
        run: ruff check .

      - name: pytest
        run: pytest
`
}

func ciWorkflowTypeScript() string {
	return `# Generated by ` + "`clawtool mcp new`" + `. Minimal CI gate per ADR-019.
# Extend with the checks your project actually needs.
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
`
}

func renderMcpToml(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `clawtool mcp new`. Source of truth\n")
	fmt.Fprintf(&b, "# for `clawtool mcp list` / `mcp install` discovery.\n\n")
	fmt.Fprintf(&b, "[project]\n")
	fmt.Fprintf(&b, "name        = %q\n", s.Name)
	fmt.Fprintf(&b, "description = %q\n", s.Description)
	fmt.Fprintf(&b, "language    = %q\n", strings.ToLower(s.Language))
	if t := strings.ToLower(s.Transport); t != "" {
		fmt.Fprintf(&b, "transport   = %q\n", t)
	} else {
		fmt.Fprintf(&b, "transport   = \"stdio\"\n")
	}
	if p := strings.ToLower(s.Packaging); p != "" {
		fmt.Fprintf(&b, "packaging   = %q\n", p)
	} else {
		fmt.Fprintf(&b, "packaging   = \"native\"\n")
	}
	fmt.Fprintf(&b, "managed_by  = \"clawtool\"\n\n")

	for _, t := range s.Tools {
		fmt.Fprintf(&b, "[[tools]]\n")
		fmt.Fprintf(&b, "name        = %q\n", t.Name)
		fmt.Fprintf(&b, "description = %q\n", t.Description)
		schema := strings.TrimSpace(t.Schema)
		if schema == "" {
			schema = `{"type":"object","properties":{}}`
		}
		fmt.Fprintf(&b, "schema      = %s\n\n", strconvQuoteTOML(schema))
	}
	return b.String()
}

// strconvQuoteTOML escapes a JSON-shaped string into a TOML
// triple-quoted literal so we don't have to backslash-escape
// double quotes inside a JSON Schema. Cheap; a real TOML library
// is overkill for one field.
func strconvQuoteTOML(s string) string {
	if !strings.Contains(s, `"""`) {
		return "\"\"\"" + s + "\"\"\""
	}
	// Fallback: marshal as a normal TOML string with escaped quotes.
	b, _ := json.Marshal(s)
	return string(b)
}

func renderReadme(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", s.Name)
	fmt.Fprintf(&b, "%s\n\n", s.Description)
	fmt.Fprintf(&b, "Generated by `clawtool mcp new`. Language: **%s**, transport: **%s**.\n\n",
		s.Language, defaultIfEmpty(s.Transport, "stdio"))

	fmt.Fprintf(&b, "## Build & run\n\n")
	switch strings.ToLower(s.Language) {
	case "go":
		fmt.Fprintf(&b, "```sh\nmake build\n./bin/%s\n```\n\n", s.Name)
	case "python":
		fmt.Fprintf(&b, "```sh\npip install -e .\npython -m %s\n```\n\n", goIdent(s.Name))
	case "typescript":
		fmt.Fprintf(&b, "```sh\nnpm install\nnpm run build\nnode dist/server.js\n```\n\n")
	}
	if strings.ToLower(s.Packaging) == "docker" {
		fmt.Fprintf(&b, "Docker image:\n\n```sh\ndocker build -t %s:latest .\ndocker run -i --rm %s:latest\n```\n\n", s.Name, s.Name)
	}

	fmt.Fprintf(&b, "## Register with clawtool\n\n")
	fmt.Fprintf(&b, "```sh\nclawtool mcp install . --as %s\nclawtool serve\n```\n\n", s.Name)
	fmt.Fprintf(&b, "This writes `[sources.%s]` into `~/.config/clawtool/config.toml` so\n", s.Name)
	fmt.Fprintf(&b, "every clawtool surface (CLI, MCP, HTTP gateway) sees the new server.\n\n")

	fmt.Fprintf(&b, "## Tools\n\n")
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "- `%s` — %s\n", t.Name, t.Description)
	}
	return b.String()
}

func gitignoreFor(language string) string {
	common := "# clawtool-generated\n.clawtool/state/\n*.log\n\n"
	switch strings.ToLower(language) {
	case "go":
		return common + "# Go\n/bin/\n/dist/\n*.test\n*.out\nvendor/\n"
	case "python":
		return common + "# Python\n__pycache__/\n*.py[cod]\n*.egg-info/\n.venv/\nbuild/\ndist/\n"
	case "typescript":
		return common + "# Node\nnode_modules/\ndist/\n.npm/\n"
	}
	return common
}

func renderClaudePlugin(s Spec) string {
	// Conservative shape — mirrors the documented plugin.json
	// fields. Operators tweak after generation; we just stub
	// what's required.
	manifest := map[string]any{
		"name":        s.Name,
		"version":     "0.1.0",
		"description": s.Description,
		"mcp": map[string]any{
			"command": defaultLaunchCommand(s),
		},
	}
	b, _ := json.MarshalIndent(manifest, "", "  ")
	return string(b) + "\n"
}

func renderMarketplaceTemplate(s Spec) string {
	// Operators-managed registry shape. Stub only — they edit
	// repo URL + maintainer fields after the first push.
	return fmt.Sprintf(`{
  "schema_version": "1",
  "name": "%s-marketplace",
  "description": "marketplace listing for %s",
  "plugins": [
    {
      "name": "%s",
      "repo": "https://github.com/<your-org>/%s",
      "ref": "main",
      "directory": "."
    }
  ]
}
`, s.Name, s.Name, s.Name, s.Name)
}

// defaultLaunchCommand returns the argv array a Claude plugin
// manifest references for stdio transport. Adapters override at
// install time when the binary path differs from the default.
func defaultLaunchCommand(s Spec) []string {
	switch strings.ToLower(s.Language) {
	case "go":
		return []string{"./bin/" + s.Name}
	case "python":
		return []string{"python", "-m", goIdent(s.Name)}
	case "typescript":
		return []string{"node", "dist/server.js"}
	}
	return []string{"./bin/" + s.Name}
}

// goIdent normalises a kebab-case project name into the
// snake-case-ish module-friendly identifier the Python and Go
// scaffolds use.
func goIdent(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

func defaultIfEmpty(v, dflt string) string {
	if strings.TrimSpace(v) == "" {
		return dflt
	}
	return v
}
