// Package mcpgen — language-agnostic files every scaffolded
// project gets. .clawtool/mcp.toml is the discovery marker `mcp
// list` walks for; .claude-plugin/ is the optional manifest from
// ADR-019.
package mcpgen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// commonFiles returns the always-on artifacts: README, mcp.toml,
// .gitignore, and (when spec.Plugin is true) the
// .claude-plugin/plugin.json + marketplace.json.template.
func commonFiles(spec Spec) []File {
	out := []File{
		{Path: ".clawtool/mcp.toml", Body: renderMcpToml(spec)},
		{Path: "README.md", Body: renderReadme(spec)},
		{Path: ".gitignore", Body: gitignoreFor(spec.Language)},
	}
	if spec.Plugin {
		out = append(out, File{
			Path: ".claude-plugin/plugin.json",
			Body: renderClaudePlugin(spec),
		})
		out = append(out, File{
			Path: ".claude-plugin/marketplace.json.template",
			Body: renderMarketplaceTemplate(spec),
		})
	}
	return out
}

func renderMcpToml(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `clawtool mcp new`. Source of truth\n")
	fmt.Fprintf(&b, "# for `clawtool mcp list` / `mcp install` discovery.\n\n")
	fmt.Fprintf(&b, "[project]\n")
	fmt.Fprintf(&b, "name        = %q\n", s.Name)
	fmt.Fprintf(&b, "description = %q\n", s.Description)
	fmt.Fprintf(&b, "language    = %q\n", strings.ToLower(s.Language))
	if t := strings.ToLower(s.Transport); t != "" {
		fmt.Fprintf(&b, "transport   = %q\n", t)
	} else {
		fmt.Fprintf(&b, "transport   = \"stdio\"\n")
	}
	if p := strings.ToLower(s.Packaging); p != "" {
		fmt.Fprintf(&b, "packaging   = %q\n", p)
	} else {
		fmt.Fprintf(&b, "packaging   = \"native\"\n")
	}
	fmt.Fprintf(&b, "managed_by  = \"clawtool\"\n\n")

	for _, t := range s.Tools {
		fmt.Fprintf(&b, "[[tools]]\n")
		fmt.Fprintf(&b, "name        = %q\n", t.Name)
		fmt.Fprintf(&b, "description = %q\n", t.Description)
		schema := strings.TrimSpace(t.Schema)
		if schema == "" {
			schema = `{"type":"object","properties":{}}`
		}
		fmt.Fprintf(&b, "schema      = %s\n\n", strconvQuoteTOML(schema))
	}
	return b.String()
}

// strconvQuoteTOML escapes a JSON-shaped string into a TOML
// triple-quoted literal so we don't have to backslash-escape
// double quotes inside a JSON Schema. Cheap; a real TOML library
// is overkill for one field.
func strconvQuoteTOML(s string) string {
	if !strings.Contains(s, `"""`) {
		return "\"\"\"" + s + "\"\"\""
	}
	// Fallback: marshal as a normal TOML string with escaped quotes.
	b, _ := json.Marshal(s)
	return string(b)
}

func renderReadme(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", s.Name)
	fmt.Fprintf(&b, "%s\n\n", s.Description)
	fmt.Fprintf(&b, "Generated by `clawtool mcp new`. Language: **%s**, transport: **%s**.\n\n",
		s.Language, defaultIfEmpty(s.Transport, "stdio"))

	fmt.Fprintf(&b, "## Build & run\n\n")
	switch strings.ToLower(s.Language) {
	case "go":
		fmt.Fprintf(&b, "```sh\nmake build\n./bin/%s\n```\n\n", s.Name)
	case "python":
		fmt.Fprintf(&b, "```sh\npip install -e .\npython -m %s\n```\n\n", goIdent(s.Name))
	case "typescript":
		fmt.Fprintf(&b, "```sh\nnpm install\nnpm run build\nnode dist/server.js\n```\n\n")
	}
	if strings.ToLower(s.Packaging) == "docker" {
		fmt.Fprintf(&b, "Docker image:\n\n```sh\ndocker build -t %s:latest .\ndocker run -i --rm %s:latest\n```\n\n", s.Name, s.Name)
	}

	fmt.Fprintf(&b, "## Register with clawtool\n\n")
	fmt.Fprintf(&b, "```sh\nclawtool mcp install . --as %s\nclawtool serve\n```\n\n", s.Name)
	fmt.Fprintf(&b, "This writes `[sources.%s]` into `~/.config/clawtool/config.toml` so\n", s.Name)
	fmt.Fprintf(&b, "every clawtool surface (CLI, MCP, HTTP gateway) sees the new server.\n\n")

	fmt.Fprintf(&b, "## Tools\n\n")
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "- `%s` — %s\n", t.Name, t.Description)
	}
	return b.String()
}

func gitignoreFor(language string) string {
	common := "# clawtool-generated\n.clawtool/state/\n*.log\n\n"
	switch strings.ToLower(language) {
	case "go":
		return common + "# Go\n/bin/\n/dist/\n*.test\n*.out\nvendor/\n"
	case "python":
		return common + "# Python\n__pycache__/\n*.py[cod]\n*.egg-info/\n.venv/\nbuild/\ndist/\n"
	case "typescript":
		return common + "# Node\nnode_modules/\ndist/\n.npm/\n"
	}
	return common
}

func renderClaudePlugin(s Spec) string {
	// Conservative shape — mirrors the documented plugin.json
	// fields. Operators tweak after generation; we just stub
	// what's required.
	manifest := map[string]any{
		"name":        s.Name,
		"version":     "0.1.0",
		"description": s.Description,
		"mcp": map[string]any{
			"command": defaultLaunchCommand(s),
		},
	}
	b, _ := json.MarshalIndent(manifest, "", "  ")
	return string(b) + "\n"
}

func renderMarketplaceTemplate(s Spec) string {
	// Operators-managed registry shape. Stub only — they edit
	// repo URL + maintainer fields after the first push.
	return fmt.Sprintf(`{
  "schema_version": "1",
  "name": "%s-marketplace",
  "description": "marketplace listing for %s",
  "plugins": [
    {
      "name": "%s",
      "repo": "https://github.com/<your-org>/%s",
      "ref": "main",
      "directory": "."
    }
  ]
}
`, s.Name, s.Name, s.Name, s.Name)
}

// defaultLaunchCommand returns the argv array a Claude plugin
// manifest references for stdio transport. Adapters override at
// install time when the binary path differs from the default.
func defaultLaunchCommand(s Spec) []string {
	switch strings.ToLower(s.Language) {
	case "go":
		return []string{"./bin/" + s.Name}
	case "python":
		return []string{"python", "-m", goIdent(s.Name)}
	case "typescript":
		return []string{"node", "dist/server.js"}
	}
	return []string{"./bin/" + s.Name}
}

// goIdent normalises a kebab-case project name into the
// snake-case-ish module-friendly identifier the Python and Go
// scaffolds use.
func goIdent(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

func defaultIfEmpty(v, dflt string) string {
	if strings.TrimSpace(v) == "" {
		return dflt
	}
	return v
}
