// Package mcpgen — Go adapter (ADR-007: wraps mark3labs/mcp-go).
package mcpgen

import (
	"fmt"
	"strings"
)

type goAdapter struct{}

func init() { Register(goAdapter{}) }

func (goAdapter) Language() string { return "go" }

func (goAdapter) Plan(s Spec) ([]File, error) {
	module := goModule(s.Name)
	files := []File{
		{
			Path: "go.mod",
			Body: fmt.Sprintf("module %s\n\ngo 1.22\n\nrequire github.com/mark3labs/mcp-go v0.49.0\n", module),
		},
		{Path: "Makefile", Body: goMakefile(s.Name)},
		{Path: fmt.Sprintf("cmd/%s/main.go", s.Name), Body: goMain(s, module)},
		{Path: "internal/tools/example.go", Body: goExampleTool(s)},
		{Path: "internal/tools/example_test.go", Body: goExampleToolTest()},
	}
	if strings.ToLower(s.Packaging) == "docker" {
		files = append(files, File{Path: "Dockerfile", Body: goDockerfile(s.Name)})
	}
	return files, nil
}

func goModule(name string) string {
	// Conservative — the operator usually rewrites this to their
	// org path. Default to a clawtool-namespaced placeholder.
	return "github.com/example/" + name
}

func goMakefile(name string) string {
	return fmt.Sprintf(`# clawtool mcp new — Go scaffold

GO ?= go
BIN := bin/%s

.PHONY: build run install clean

build:
	@mkdir -p bin
	$(GO) build -o $(BIN) ./cmd/%s
	@echo "✓ built $(BIN)"

run: build
	$(BIN)

install: build
	clawtool mcp install . --as %s

clean:
	rm -rf bin
`, name, name, name)
}

func goMain(s Spec, module string) string {
	var b strings.Builder
	fmt.Fprintf(&b, `// Generated by clawtool mcp new.
// %s
package main

import (
	"fmt"
	"os"

	"github.com/mark3labs/mcp-go/server"

	"%s/internal/tools"
)

func main() {
	s := server.NewMCPServer("%s", "0.1.0",
		server.WithToolCapabilities(true),
		server.WithLogging(),
	)
`, s.Description, module, s.Name)

	for _, t := range s.Tools {
		fmt.Fprintf(&b, "\ttools.Register%s(s)\n", goCamel(t.Name))
	}

	fmt.Fprintf(&b, `
	if err := server.ServeStdio(s); err != nil {
		fmt.Fprintf(os.Stderr, "%s: %%v\n", err)
		os.Exit(1)
	}
}
`, s.Name)
	return b.String()
}

func goExampleTool(s Spec) string {
	t := s.Tools[0]
	var b strings.Builder
	fmt.Fprintf(&b, `// Generated by clawtool mcp new.
package tools

import (
	"context"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// Register%s adds the %q tool. Edit the handler to do the real work.
func Register%s(s *server.MCPServer) {
	s.AddTool(
		mcp.NewTool(
			%q,
			mcp.WithDescription(%q),
			mcp.WithString("input",
				mcp.Description("Free-form input — replace with your real schema."),
				mcp.Required()),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			input, err := req.RequireString("input")
			if err != nil {
				return mcp.NewToolResultError("missing required argument: input"), nil
			}
			// TODO(template): replace with real implementation.
			return mcp.NewToolResultText("you said: " + input), nil
		},
	)
}
`, goCamel(t.Name), t.Name, goCamel(t.Name), t.Name, t.Description)
	return b.String()
}

func goExampleToolTest() string {
	return `package tools

import "testing"

func TestPackageCompiles(t *testing.T) {
	// Smoke test — every scaffold ships at least one passing
	// test so ` + "`go test`" + ` is meaningful from the start.
}
`
}

func goDockerfile(name string) string {
	return fmt.Sprintf(`# Multi-stage Docker build for %s.
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /out/%s ./cmd/%s

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/%s /usr/local/bin/%s
ENTRYPOINT ["/usr/local/bin/%s"]
`, name, name, name, name, name, name)
}

// goCamel converts snake_case to UpperCamelCase for Go identifiers.
func goCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}
