// Package mcpgen — Python adapter (ADR-007: wraps fastmcp).
package mcpgen

import (
	"fmt"
	"strings"
)

type pythonAdapter struct{}

func init() { Register(pythonAdapter{}) }

func (pythonAdapter) Language() string { return "python" }

func (pythonAdapter) Plan(s Spec) ([]File, error) {
	pkg := goIdent(s.Name)
	files := []File{
		{Path: "pyproject.toml", Body: pyProject(s, pkg)},
		{Path: "Makefile", Body: pyMakefile(s.Name, pkg)},
		{Path: fmt.Sprintf("src/%s/__init__.py", pkg), Body: ""},
		{Path: fmt.Sprintf("src/%s/__main__.py", pkg), Body: pyMain(pkg)},
		{Path: fmt.Sprintf("src/%s/server.py", pkg), Body: pyServer(s, pkg)},
		{Path: fmt.Sprintf("src/%s/tools/__init__.py", pkg), Body: pyToolsInit(s)},
		{Path: fmt.Sprintf("src/%s/tools/%s.py", pkg, s.Tools[0].Name), Body: pyExampleTool(s)},
		{Path: "tests/test_smoke.py", Body: pyTest()},
	}
	if strings.ToLower(s.Packaging) == "docker" {
		files = append(files, File{Path: "Dockerfile", Body: pyDockerfile(pkg)})
	}
	return files, nil
}

func pyProject(s Spec, pkg string) string {
	return fmt.Sprintf(`# Generated by clawtool mcp new (ADR-019).
[project]
name = "%s"
version = "0.1.0"
description = "%s"
requires-python = ">=3.10"
dependencies = [
  "fastmcp>=0.4",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
`, s.Name, escapeForToml(s.Description))
}

func escapeForToml(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}

func pyMakefile(name, pkg string) string {
	return fmt.Sprintf(`# clawtool mcp new (ADR-019) — Python scaffold

PY ?= python3
PIP ?= pip

.PHONY: install dev run test clean

install:
	$(PIP) install -e .

dev: install
	$(PY) -m %s

run: install
	$(PY) -m %s

test:
	$(PY) -m pytest -q

clean:
	rm -rf build dist *.egg-info __pycache__

mcp-install: install
	clawtool mcp install . --as %s
`, pkg, pkg, name)
}

func pyMain(pkg string) string {
	return fmt.Sprintf(`# Generated by clawtool mcp new (ADR-019).
from %s.server import build
from fastmcp import FastMCP


def main() -> None:
    server: FastMCP = build()
    server.run()


if __name__ == "__main__":
    main()
`, pkg)
}

func pyServer(s Spec, pkg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by clawtool mcp new (ADR-019).
"""%s"""

from fastmcp import FastMCP

`, s.Description)
	fmt.Fprintf(&b, "from .tools import register_all\n\n\n")
	fmt.Fprintf(&b, `def build() -> FastMCP:
    server = FastMCP(%q)
    register_all(server)
    return server
`, s.Name)
	return b.String()
}

func pyToolsInit(s Spec) string {
	var b strings.Builder
	b.WriteString("# Auto-generated. Add new tools and update register_all.\n\n")
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "from .%s import register as _register_%s  # noqa: F401\n", t.Name, t.Name)
	}
	b.WriteString("\n\ndef register_all(server) -> None:\n")
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "    _register_%s(server)\n", t.Name)
	}
	return b.String()
}

func pyExampleTool(s Spec) string {
	t := s.Tools[0]
	return fmt.Sprintf(`# Generated by clawtool mcp new (ADR-019).
"""%s"""

from fastmcp import FastMCP


def register(server: FastMCP) -> None:
    @server.tool(name=%q, description=%q)
    def %s(input: str) -> str:
        """%s"""
        # TODO: replace with real implementation.
        return f"you said: {input}"
`, t.Description, t.Name, t.Description, t.Name, t.Description)
}

func pyTest() string {
	return `def test_package_imports():
    """Smoke test — module imports cleanly."""
    pass
`
}

func pyDockerfile(pkg string) string {
	return fmt.Sprintf(`FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir -e .
ENTRYPOINT ["python", "-m", "%s"]
`, pkg)
}
