// Package mcpgen — TypeScript adapter (ADR-007: wraps
// @modelcontextprotocol/sdk).
package mcpgen

import (
	"fmt"
	"strings"
)

type tsAdapter struct{}

func init() { Register(tsAdapter{}) }

func (tsAdapter) Language() string { return "typescript" }

func (tsAdapter) Plan(s Spec) ([]File, error) {
	files := []File{
		{Path: "package.json", Body: tsPackageJSON(s)},
		{Path: "tsconfig.json", Body: tsConfig()},
		{Path: "Makefile", Body: tsMakefile(s.Name)},
		{Path: "src/server.ts", Body: tsServer(s)},
		{Path: fmt.Sprintf("src/tools/%s.ts", s.Tools[0].Name), Body: tsExampleTool(s)},
		{Path: "test/example.test.ts", Body: tsTest()},
	}
	if strings.ToLower(s.Packaging) == "docker" {
		files = append(files, File{Path: "Dockerfile", Body: tsDockerfile()})
	}
	return files, nil
}

func tsPackageJSON(s Spec) string {
	return fmt.Sprintf(`{
  "name": "%s",
  "version": "0.1.0",
  "description": "%s",
  "type": "module",
  "main": "dist/server.js",
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "start": "node dist/server.js",
    "test": "node --test"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0",
    "@types/node": "^20.0.0"
  }
}
`, s.Name, escapeForJSON(s.Description))
}

func escapeForJSON(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	return strings.ReplaceAll(s, `"`, `\"`)
}

func tsConfig() string {
	return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true
  },
  "include": ["src/**/*"]
}
`
}

func tsMakefile(name string) string {
	return fmt.Sprintf(`# clawtool mcp new — TypeScript scaffold

NPM ?= npm

.PHONY: install build run test clean mcp-install

install:
	$(NPM) install

build: install
	$(NPM) run build

run: build
	node dist/server.js

test: build
	$(NPM) test

clean:
	rm -rf node_modules dist

mcp-install: build
	clawtool mcp install . --as %s
`, name)
}

func tsServer(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, `// Generated by clawtool mcp new.
// %s

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

`, s.Description)
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "import { register as register_%s } from \"./tools/%s.js\";\n", t.Name, t.Name)
	}
	fmt.Fprintf(&b, `
async function main(): Promise<void> {
  const server = new Server(
    { name: %q, version: "0.1.0" },
    { capabilities: { tools: {} } },
  );
`, s.Name)
	for _, t := range s.Tools {
		fmt.Fprintf(&b, "  register_%s(server);\n", t.Name)
	}
	fmt.Fprintf(&b, `
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`)
	return b.String()
}

func tsExampleTool(s Spec) string {
	t := s.Tools[0]
	return fmt.Sprintf(`// Generated by clawtool mcp new.
// %s

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

export function register(server: Server): void {
  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: [
      {
        name: %q,
        description: %q,
        inputSchema: {
          type: "object",
          properties: {
            input: { type: "string", description: "Free-form input — replace with your real schema." },
          },
          required: ["input"],
        },
      },
    ],
  }));

  server.setRequestHandler(CallToolRequestSchema, async (req) => {
    if (req.params.name !== %q) {
      throw new Error(`+"`"+`unknown tool ${req.params.name}`+"`"+`);
    }
    const input = String(req.params.arguments?.input ?? "");
    // TODO(template): replace with real implementation.
    return {
      content: [{ type: "text", text: `+"`"+`you said: ${input}`+"`"+` }],
    };
  });
}
`, t.Description, t.Name, t.Description, t.Name)
}

func tsTest() string {
	return `import { test } from "node:test";
import assert from "node:assert/strict";

test("package compiles", () => {
  assert.ok(true);
});
`
}

func tsDockerfile() string {
	return `FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --no-audit --no-fund
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package.json ./
ENTRYPOINT ["node", "dist/server.js"]
`
}
