// Package registry — TypeScript stub export for code-mode hosts.
//
// Anthropic's "Code execution with MCP" recipe (and Cloudflare's
// earlier "Code Mode" pattern) presents the MCP tool catalog as a
// TypeScript file tree the agent imports from. Quoted reduction
// from that recipe: 150 K → 2 K tokens (98.7%) on heavy tool-call
// loops. The agent writes code instead of round-tripping each
// `tools/call`.
//
// `clawtool tools export-typescript --output <dir>` walks the
// manifest and emits one `.ts` file per registered tool, plus a
// barrel `index.ts`. The MVP shape is minimal: tool name,
// description (docstring), and a typed function signature whose
// input + output are `any` for now. Full JSON-Schema → TypeScript
// translation lands in a follow-up cut once we decide how to
// represent oneOf / $ref / nested objects without bringing in a
// full schema-codegen dependency.
//
// The point of the MVP: operators using a code-mode host (Codex
// 0.125+ rollout-tracing now records "code-mode edges"; Anthropic
// blog endorses the pattern) can already adopt clawtool's tool
// catalog as a TypeScript module today, with the agent reading the
// docstring to learn what each tool does. Type fidelity arrives
// incrementally.
package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ExportTypeScript writes one .ts file per ToolSpec into outDir,
// plus an index.ts that re-exports every tool. Returns the list of
// files created (relative to outDir) so the CLI can echo them back
// to the operator.
//
// outDir is created when missing. Existing files in outDir are
// overwritten silently — the export is meant to be idempotent and
// repeatable on every manifest change.
func (m *Manifest) ExportTypeScript(outDir string) ([]string, error) {
	if m == nil || len(m.specs) == 0 {
		return nil, fmt.Errorf("registry: manifest empty; nothing to export")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, fmt.Errorf("registry: mkdir %s: %w", outDir, err)
	}

	written := make([]string, 0, len(m.specs)+1)
	exports := make([]string, 0, len(m.specs))

	for _, spec := range m.specs {
		body := renderToolStub(spec)
		path := filepath.Join(outDir, spec.Name+".ts")
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return nil, fmt.Errorf("registry: write %s: %w", path, err)
		}
		written = append(written, spec.Name+".ts")
		exports = append(exports, spec.Name)
	}
	// Stable order in the barrel — manifest order is meaningful
	// (gate-driven), but the barrel reads better alphabetically
	// since a code-mode host is browsing it as a directory listing.
	sort.Strings(exports)
	sort.Strings(written)

	idxPath := filepath.Join(outDir, "index.ts")
	if err := os.WriteFile(idxPath, []byte(renderBarrel(exports)), 0o644); err != nil {
		return nil, fmt.Errorf("registry: write %s: %w", idxPath, err)
	}
	written = append(written, "index.ts")
	sort.Strings(written)
	return written, nil
}

// renderToolStub emits the per-tool `.ts` file. Format:
//
//   - Header comment (regenerate hint).
//   - JSDoc block carrying spec.Description verbatim.
//   - `declare` function signature (no implementation — the host's
//     code-mode runtime injects the bridge to mcp__clawtool__<Name>
//     at execution time).
//
// The `any` types are intentional MVP scope. The follow-up commit
// will fold per-tool input/output schemas into the manifest and
// emit typed interfaces.
func renderToolStub(spec ToolSpec) string {
	var b strings.Builder
	b.WriteString("// Generated by `clawtool tools export-typescript`.\n")
	b.WriteString("// Do not edit — re-run the command to refresh.\n")
	b.WriteString("// Category: " + string(spec.Category) + "\n")
	if spec.Gate != "" {
		b.WriteString("// Config gate: " + spec.Gate + "\n")
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	for _, line := range wrapForJSDoc(spec.Description, 78) {
		b.WriteString(" * " + line + "\n")
	}
	if len(spec.Keywords) > 0 {
		b.WriteString(" *\n")
		b.WriteString(" * @keywords " + strings.Join(spec.Keywords, ", ") + "\n")
	}
	b.WriteString(" */\n")
	b.WriteString("export declare function ")
	b.WriteString(spec.Name)
	b.WriteString("(input: any): Promise<any>;\n")
	return b.String()
}

// renderBarrel emits the index.ts re-exporter so a code-mode host
// can `import { Bash, Read, Edit } from "./clawtool-stubs"` without
// touching individual files.
func renderBarrel(names []string) string {
	var b strings.Builder
	b.WriteString("// Generated by `clawtool tools export-typescript`.\n")
	b.WriteString("// Do not edit — re-run the command to refresh.\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "export { %s } from %q;\n", n, "./"+n)
	}
	return b.String()
}

// wrapForJSDoc breaks a paragraph at word boundaries to keep
// generated JSDoc readable. Falls back to hard-wrap on tokens
// longer than the limit (URLs, hashes).
func wrapForJSDoc(s string, width int) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return []string{""}
	}
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{""}
	}
	var out []string
	cur := words[0]
	for _, w := range words[1:] {
		if len(cur)+1+len(w) > width {
			out = append(out, cur)
			cur = w
		} else {
			cur += " " + w
		}
	}
	out = append(out, cur)
	return out
}
